name: CI-Multi-Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  with-checkout-job:
    name: With Checkout
    runs-on: "ubuntu-latest"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .
      - name: Install Python
        run: |
          sudo apt-get install python3 python3-pip
      - name: Build
        run: |
          pip install --upgrade build
          python -m build
          tree .
      - name: Artifacts
        run: |
          rm dist/pack-0.0.0.tar.gz
          mv script.py dist/script.py
          tree .
