name: CI-Multi-Jobs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  Build:
    name: Build Phase
    runs-on: "ubuntu-latest"
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Install tree & run
        run: |
          sudo apt-get install -y tree
          tree .
      - name: Install Python
        run: |
          sudo apt-get install python3 python3-pip
      - name: Build
        run: |
          pip install --upgrade build
          python -m build
          tree .
      - name: Artifacts
        run: |
          rm dist/pack-0.0.0.tar.gz
          mv script.py dist/script.py
          tree .
      - name: Artifacts upload
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: dist/
      - run: tree .
  deploy:
    name: Deploy phase
    runs-on: "ubuntu-latest"
    needs: dev
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: my-artifact
    - name: Display structure of downloaded files
      run: ls -R
    - name: run
      run: |
        pip install pack-0.0.0-py3-none-any.whl
        python script.py
